### PR TITLE
[TASK] Drop support for PHP < 5.6

### PR DESCRIPTION
**Pull request by oliverklee**
PHP 5.4 and PHP 5.5 have reached their end of life and thus are not
supported anymore (not even with security updates). So PHPList will
not support it anymore, either.

### CODE REVIEW

**Comment by liayn** [comment]
sorry for asking a bit too late. Why are you even considering 5.6 any longer?
PHP7.1 is out, all major hosters have PHP7 available.
5.6 has end of life in a little less than a year

**Comment by oliverklee** [comment]
I was being conservative after my experience trying to drop support for old PHP versions in phpList 3 …

**Comment by liayn** [comment]
Benefit of PHP7: Stronger type system.

This is a new product (full rewrite), so you need to target up to date systems, when the first stable release is planned. (Remember the hard decision for PHP5.5 as minimum for TYPO3 7? It was a fight. In the end it was the best decision ever taken)

**Comment by oliverklee** [comment]
Okay, I'll also discussion this on the dev list. Thanks for persisting!

**Comment by oliverklee** [comment]
BTW, are you on the dev list as well so you could participate in the ensuing discussions?

**Comment by liayn** [comment]
Nope, I'm a (mostly silent) user of phplist for one of our customers. And if overloaded with stuff to do for TYPO3. ;-)
So thanks for invitation. I'm just trying to give hints of experiences, but will not insist/interfere if things run differently.

**Comment by michield** [comment]
I agree, we can go PHP7 only on this project.

**Comment by oliverklee** [comment]
@liayn All right. Then looking forward to your occasional hint of experiences. :heart:

**Comment by oliverklee** [comment]
I've entered #27 for going PHP-7-only.

**Pull request merged**
