### PR TITLE
[BUGFIX] Load an existing config file in the unit tests

### PR DESCRIPTION
**Pull request by oliverklee**
The unit tests still do not pass completely as they cannot connect to any
DB on Travis yet. This will be part of a separate PR.

(And unit tests should not connect to a real database.)

### CODE REVIEW

**Comment by michield** [comment]
Can you redo this one? It doesn't merge cleanly currently.

**Comment by oliverklee** [comment]
I've rebased, resolved the conflicts, and repushed.

**Comment by oliverklee** [comment]
@michield When merging, I propose using the "squash and merge" option instead of "create a merge commit". This will help keep the history clean. Thanks!

**Comment by michield** [comment]
ok, will do

**Pull request merged**
